application.name=Ghidra
application.version=10.3.1
application.release.name=PUBLIC
application.layout.version=1
application.gradle.min=7.3
application.gradle.max=
application.java.min=17
application.java.max=
application.java.compiler=17
application.build.date=2023-Jun-14 1629 EDT
application.build.date.short=20230614
application.revision.ghidra=69289358f2f4f0ba180fd44b6b4af69290763086
application.revision.ghidra.bin=3c7ff7dc27fabd558ea32ae3ce6df9725a3efe4e
